const stations = {
    noticias: [
        { name: "Radio Klara (València 104.4FM)", url: "https://cervera.eldialdigital.com:21111/stream" },
        { name: "Radio QK (Uviéu 107.2FM)", url: "https://icecast.radioqk.org:8443/radioqk_master.mp3" },
        { name: "Radio Vallekas (107.5FM)", url: "https://radio.radiobot.org/listen/rvk/rvk.mp3" },
        { name: "Radio Kras (Xixón 105.0FM)", url: "https://giss.tv:666/RadioKras.mp3" },
        { name: "Color Comunitaria (Málaga 107.3FM)", url: "https://cervera.eldialdigital.com:21201/stream" },
        { name: "Cuac FM (A Coruña 103.4FM)", url: "https://streaming.cuacfm.org/cuacfm-128k.mp3" },
        { name: "Radio Guiniguada (Las Palmas de Gran Canaria 89.4FM)", url: "https://streamtotal.net/proxy/guiniguada/;" },
        { name: "Radio Espiritrompa (Alto Aragón 102.2FM)", url: "https://radiobot.radioslibres.info/listen/radio_espiritrompa/radio.mp3" },
    ],
    musica: [
        { name: "Almenara Radio (Madrid 106.7FM)", url: "https://cervera.eldialdigital.com:25211/stream" },
        { name: "Radio Argayo (Radio Libre en Cantabria)", url: "https://radiobot.radioslibres.info/radio/8030/radio.ogg?_=1" },
        { name: "Radio La Granja (Zaragoza 102.1FM)", url: "https://radiobot.radioslibres.info/listen/radio_la_granja/rlg.mp3" },
        { name: "Eco Leganés (Madrid)", url: "https://cervera.eldialdigital.com:25191/stream" },
        { name: "Ovejas Negrax (Madrid)", url: "https://radio.radiobot.org/listen/ovejas/ovejasnegrax.mp3" },
        { name: "OMC Onda Merlín Comunitaria (Villaverde-Madrid 107.3FM)", url: "https://radio.radiobot.org/listen/omc/directo.mp3" },
        { name: "Radio Enlace (Hortaleza-Madrid 107.5FM)", url: "https://cervera.eldialdigital.com:25121/stream" },
        { name: "Radio Iris 7 (Aranda de Duero 100.0FM)", url: "https://sonic.sistemahost.es/8244/stream" },
    ],
    generales: [
        { name: "Siberia FM (Vitoria-Gasteiz 91.8FM)", url: "https://stream.euskonet.eus/siberia?1762901374198" },
        { name: "Radio Xata (Pinto-Madrid)", url: "https://radio.radiobot.org/listen/xata/radio.mp3" },
        { name: "Radiópolis (Sevilla 92.3FM)", url: "https://radio.andaina.net/8038/stream" },
        { name: "RTVC  Ràdio Televisió Cardedeu (Barcelona 90.7FM)", url: "https://azuracast.rtvc.cat/radio/8000/radio.mp3" },
        { name: "Radio Oasis (Salamanca 105.9FM)", url: "https://cervera.eldialdigital.com:21141/stream" },
        { name: "Hala Bedi Irratia (Gasteiz 95.6FM)", url: "https://stream.halabedi.eus/hb2_64.mp3" },
        { name: "Onda Latina (La Latina-Madrid 87.6FM)", url: "https://cervera.eldialdigital.com:21131/stream" },
        { name: "Irola Irratia (Bilbo 107.5FM)", url: "https://s.streampunk.cc/_stream/irola_irratia.mp3" },
    ],
    libre: [
        { name: "Eguzki Irratia (Iruñea 107.0FM eta Iruñerrian 91.0FM)", url: "https://streaming.eguzki.eus/eguzki.mp3" },
        { name: "Radio Piratona (Vigo 106.1FM)", url: "https://zeppelin.streampunk.cc/_stream/radiopiratona.ogg" },
        { name: "Radio Topo (Zaragoza 101.8FM)", url: "https://radiobot.radioslibres.info/listen/radio_topo/radio96.mp3" },
        { name: "Radio Sintonía (Puente Genil-Córdoba 106.9FM)", url: "https://eu5.fastcast4u.com/proxy/sintoniapg?mp=/;" },
        { name: "Ágora Sol Radio (Madrid)", url: "https://cervera.eldialdigital.com:23141/stream" },
        { name: "Radio Roncudo (Bergantiños-Costa da Muerte 106.1FM)", url: "https://stream-176.zeno.fm/fzbq43mvfq3tv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJmemJxNDNtdmZxM3R2IiwiaG9zdCI6InN0cmVhbS0xNzYuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6IjJ6amhwSkdsU1MtN1Q1Ynl3cDBXUnciLCJpYXQiOjE3NjM0NzA4MjYsImV4cCI6MTc2MzQ3MDg4Nn0.rmY4msWxlGPn6JUzRYkLJw4kFOYbQdDMw2pp0bnJAIs" },
        { name: "Paradigma Radio (Córdoba 90.2FM)", url: "https://radio.andaina.net/8042/stream" },
        { name: "Radio Almaina (Granada 88.5 FM)", url: "https://radiobot.radioslibres.info/listen/radio_almaina/radio.mp3" },
    ],
    onda5: [
        { name: "Radio Kolor (Cuenca 106.2FM)", url: "http://stream20.usastreams.com:8122/stream" },
        { name: "Onda Polígono (Toledo 107.3FM)", url: "https://icecast.ondapoligono.org/stream" },
        { name: "Radio FilispiM (Ferrol 93.9FM)", url: "https://streaming.cuacfm.org/filispim.mp3" },
        { name: "Radio Pimienta (Tenerife)", url: "https://cervera.eldialdigital.com:21182/stream" },
        { name: "Electronic Music (Hirschmilch Radio)", url: "https://hirschmilch.de:7501/electronic.mp3?ts=1754176686" },
        { name: "Alpha Boys School Radio (KInsgton, Jamaica)", url: "https://alphaboys-live.streamguys1.com/alphaboys.mp3" },
        { name: "Klassik Radio (DE)", url: "https://klassikr.streamabc.net/klr-krdnational-mp3-192-8877033" },
        { name: "Soul, Smooth, Jazz (Serenade Radio UK)", url: "https://rbx2.hnux.com/http://149.202.22.75:8284/;" },
    ],
};

export { stations };